---
# tasks file for roles/jenkins
- name: install default-jre
  package:
    name: default-jre
    state: present
- name: install python3
  package:
    name: python3
    state: present
- name: install python3-setuptools
  package:
    name: python-setuptools
    state: present
- name: install python-pip packages
  package:
    name: python-pip
    state: present
- name: Download jenkins.war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
- name: Template a file to /etc/systemd/system/jenkins.service
  template:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service
  notify:
    - Restart Jenkins
- name: Flush Handlers
  meta: flush_handlers
- name: Wait until the password file shows up
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword
- shell: cat /root/.jenkins/secrets/initialAdminPassword
  register: result
#- debug:
#   msg: test
#    verbosity: 2
