---
# tasks file for roles/jenkins
- name: install java
  package:
    name: default-jre
    state: present
# - name: install python
#   package:
#     name: python3
#     state: present
# - name: install pip3
#   package:
#     name: pip3
#     state: present

# - name: install pip packages
#   pip:
#     name: virtualenv
#     state: present
#     executable: pip3
- name: download jenkins.war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/local/etc
- name: Template a file to /etc/files.conf
  template:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service
    mode: 0740
  notify:
      - restart_jenkins
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
- name: Wait until the file /root/.jenkins/secrets/initialAdminPassword is present before continuing
  wait_for:
    path: /root/.jenkins/secrets/initialAdminPassword
- name: extract password
  shell: cat /root/.jenkins/secrets/initialAdminPassword
  register: result_passd
- debug:
    var: result_passd.stdout
- name: enable service httpd and ensure it is not masked
  systemd:
    name: jenkins.service
    enabled: yes
    masked: no


